const {JSDOM}=require('jsdom'),fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const dom=new JSDOM('<header id="nav"></header><main id="app"></main><div id="toast"></div><dialog id="modal"></dialog><footer id="footer"></footer>',{url:'https://example.test/game/index.html',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window,c=dom.getInternalVMContext();
w.scrollTo=()=>{};w.structuredClone=structuredClone;w.fetch=async()=>({ok:true,json:async()=>({version:0,data:null})});w.HTMLDialogElement.prototype.showModal=function(){this.open=true};w.HTMLDialogElement.prototype.close=function(){this.open=false};
const timers=new Map();let seq=0,notes=0,stops=0;
w.setInterval=fn=>{timers.set(++seq,fn);return seq};w.clearInterval=id=>timers.delete(id);w.setTimeout=()=>++seq;w.clearTimeout=()=>{};
const param=()=>({value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}});
const node=()=>({gain:param(),frequency:param(),connect(){},disconnect(){},start(){notes++},stop(){stops++}});
w.AudioContext=class{state='running';currentTime=0;sampleRate=1000;destination={};createGain(){return node()}createOscillator(){return node()}createBuffer(n,size){return {getChannelData:()=>new Float32Array(size)}}createBufferSource(){return node()}createBiquadFilter(){return node()}resume(){return Promise.resolve()}};
const run=s=>vm.runInContext(s,c),read=f=>fs.readFileSync(__dirname+'/../public/game/'+f,'utf8');
for(const f of ['app.js','pro.js','battle-fx.js'])run(read(f));
run('state.sound=false;quickPlay();config.crit=false;config.theme=2;startMatch();renderGame()');
assert.match(w.document.querySelector('.arena').style.getPropertyValue('--arena-image'),/fire-temple/);
const initialHP=run('game.teams[0].hp');run('buzz(0);answer(1)');
assert.equal(run('game.teams[0].hp'),initialHP-10);assert.equal(run('game.teams[1].hp'),100);
assert.ok(w.document.querySelector('.fighter[data-team="0"] .fx-damage'));
assert.equal(w.document.querySelector('.fighter[data-team="1"] .fx-damage'),null);assert.equal(notes,0,'muted game does not start sounds');
run('nextQuestion();buzz(1);answer(game.questions[game.index].correct)');
assert.ok(w.document.querySelector('.fighter[data-team="0"] .fx-damage'));assert.ok(w.document.querySelector('.fighter[data-team="1"]').classList.contains('fx-attack'));
const hpBefore=run('game.teams[0].hp');run('nextQuestion();game.teams[1].energy=3;useSkill(1)');assert.equal(run('game.teams[0].hp'),hpBefore-15);assert.match(w.document.querySelector('.fx-callout').textContent,/KỸ NĂNG/);
run('state.preferences.reducedMotion=true;renderGame();buzz(0);answer(-1)');assert.equal(w.document.querySelector('.fx-bolt'),null);assert.equal(w.document.querySelector('.fx-particles'),null);assert.match(w.document.querySelector('.fx-callout').textContent,/HẾT GIỜ/);
run('toggleSound()');assert.ok(notes>0);run('toggleSound()');assert.ok(stops>0);const count=notes;run('sound(850)');assert.equal(notes,count);
run('undoRound()');assert.equal(w.document.querySelector('.fx-damage'),null);assert.equal(run('game.phase'),'waiting');
run('state.preferences.reducedMotion=false;game.teams[0].hp=90;game.teams[1].hp=20;finish()');
w.dispatchEvent(new w.HashChangeEvent('hashchange'));assert.ok(w.document.querySelector('.fx-confetti'),'route cleanup must not erase victory animation');
run('newMatch();setupMatch("team")');assert.match(w.document.querySelectorAll('.theme')[1].style.backgroundImage,/ninja-duel/);
for(const name of ['ninja-duel','fire-temple','ice-world','space-battle','comic-vs','school-arena'])assert.ok(fs.statSync(__dirname+'/../public/game/assets/arenas/'+name+'.jpg').size>100000);
console.log('PASS: battle effects target correct HP owner; skill, timeout, mute, reduced motion, undo, victory and six scene assets.');dom.window.close();
